# Отступы - 3 пробела
# Имена папок заканчиваются двоеточием. Это позволяет созавать пустые папки, папки с точками в имени и файлы без расширений
my_project:
      empty.folder:
      settings:
         __init__.py
         dev.py
         prod.py
      mainapp:
         __init__.py
         models.py
         views.py
         templates:
            mainapp:
               base.html
               index.html
      authapp:
         __init__.py
         models.py
         views.py
         templates:
            authapp:
               base.html
               index.html